### ISSUE TITLE
External/initial fields

### ISSUE THREAD

**Issue by Tissot11** [osiris-code/osiris#12]
Hi,

I summarise my questions below:

1.  According to the input_file structure, (https://osiris-code.github.io/documentation/input_format), there shouldn't be any `diag_emf{}` inserted between `emf_bound{}` and `particles{}` sections as shown in the 2D example at the bottom of the page. It does work but it only saves the self-generated fields despite an external field being present in the `input_file` and in the `diag_emf{}` sections.  I enable these `diag_emf `(after `emf_bound{} `section) and `el_mag_fld` at the end of input_file 

```
diag_emf {
  ndump_fac = 5,                     
  reports = "b3", "part_b3",
            "ext_b3",          
}

el_mag_fld
{ 
  ext_fld = "static",
  type_ext_b(3) = "unifrom",
  b0(3)= 0.0928,   
}
```

Even though, I have these blocks present, I get the following message (see the attached output file) and the simulation only saves `b3` but not `part_b3` and `ext_b3`. I am a bit confused about this...

[outOsiris-13263560.txt](https://github.com/user-attachments/files/16574090/outOsiris-13263560.txt)

2. I am interested in applying  external electrical and magnetic fields at `t=0 `in the plasma. This fields (of `"static" or "math func"` type in `Osiris`) will evolve due to plasma dynamics. It appears that it could be accomplished by either using external fields or initial fields constructions in `Osiris`? In each case, I need to save  `ext_b3 , part_b3` for external field configuration or `b3` and `part_b3` for initial field configuration? I tried all of this but I only seem to be able to save the self-generated fields and nothing else. Could you please provide a clear tip on how to save the total fields in the `diag_emf{}` block?

3. Also `ndump_fac_charge ` option listed here (https://osiris-code.github.io/osiris/reference/cathode) doesn't work in this version of Osiris.

**Comment by millerk123** [comment]
1. The emf input file sections should be in the following order: `el_mag_fld`, `emf_bound`, `emf_solver`, `smooth`, and `diag_emf`.  So your input deck should be something like
```
el_mag_fld
{ 
  ext_fld = "static",
  type_ext_b(3) = "uniform",
  b0(3)= 0.0928,   
}

diag_emf {
  ndump_fac = 5,                     
  reports = "b3", "part_b3",
            "ext_b3",          
}
```

The "b3" report is the self-consistent OSIRIS fields (excluding any external fields).  The "ext_b3" report dumps only the external fields (excluding self-consistent fields).  The "part_b3" report is the sum of the two.  Also might be helpful for you to attach your entire input deck.

2. Do you wish to impose a constant electric/magnetic field for the entire simulation, starting at `t = 0`?  If so, use the static external fields.  If you wish to initialize the simulation with some constant electric/magnetic field, then you want `type_init_b = "uniform"`.  If you do the latter, then there are no external fields, and the "b3" and "part_b3" reports will be the same: the total simulation field, including whatever initial field you specified at `t = 0`.

3. Yes, you are correct.  That is an error in the documentation.  It should instead be
```
diag_species {
  ndump_fac = 1,
  reports = "charge",
}
```

**Comment by Tissot11** [comment]
1. Thanks for your answer! Documentation and reference guide only mention in the `input_file` order  that `emf_bound` section should come before the `particles` section. The ` el_mag_fld `and `diag_emf ` sections are optional but it is not mentioned anywhere what should be their order in the `input_file` should they occur. Also it is not mentioned anywhere that in order to get `part_b3 `diagnostic you have to declare `smooth_type` in `el_mag_fld` section. Since there is no one complete or options rich `input_file` provided, it is a is a bit confusing for new people like me and I ended up spending lots of time just to figure things out by trial and error. 

2. Anyway, I attach my redacted input file here. Now I followed your suggestions (though I don't find `emf_solver` in the reference guide). You can see in the` el_mag_fld` section my initial field configuration. `Osiris` now does record correct `b1` but not `b3`, `e2` and `part_b3`.  These are still the self-generated field at `t=0` with values` 0.` If I declare `type_init_b` (commented lines in the input file) then I get the error no function specified (see the attached out file). This way of recording fields into self-generated and external ones is indeed a nice feature in `Osiris` and I could use both `init`and `ext_fld `configuration for my problem but I need to know to know how to define and save these field correctly in each case.


[d10_mi256-MA63.txt](https://github.com/user-attachments/files/16597226/d10_mi256-MA63.txt)
[outOsiris-13273654.txt](https://github.com/user-attachments/files/16597215/outOsiris-13273654.txt)

**Comment by Tissot11** [comment]
It seems that the documentation has been updated now and it appears to list the correct order.
