### ISSUE TITLE
Performing Winger transform

### ISSUE THREAD

**Issue by zhangli28** [osiris-code/osiris#16]
Hi, 

I would like to learn how to make ```Wigner transform``` of the laser pulse, for example, as done in Fig.1(c,d,e) of the following paper: https://iopscience.iop.org/article/10.1088/1367-2630/14/2/023057/pdf  

Thank you.
Zhang

**Comment by tsung1029** [comment]
Hi Zhang:

I can help you make this diagnostic.  Please download the pyVisOS library which will read OSIRIS data in python and then I can show you how to do this.  

Frank

https://github.com/UCLA-Plasma-Simulation-Group/pyVisOS



![wigner-example](https://github.com/user-attachments/assets/b9c341b3-a4ab-48dd-80b2-6eb83451f1c6)

**Comment by zhangli28** [comment]
Hi @tsung1029, 

Thank you so much. I have installed pyVisOS library and it can be loaded successfully with a test python file. 

We can assume that I have a 2D Electric field distribution of the laser pulse or a 1d electric field (as shown in your figure above). 

Now I am looking for your help .....

Thank you so many times.
Zhang

**Comment by tsung1029** [comment]
Hi:

can you email me at tsung AT physics DOT ucla DOT edu.  we can set up a zoom call

**Comment by zhangli28** [comment]
Hi @tsung1029 , 

I was able to do almost 80 % of the work. I just need to set the axis parameters properly. The Wigner transform is much easier in Matlab (and even in python) than what I was expecting. See the attached example figures I was able to do with Matlab. 

<img width="1482" alt="Wigner_test" src="https://github.com/user-attachments/assets/28409dca-04f5-4c51-a1b1-06fcf2a1c868" />

**Comment by tsung1029** [comment]
I would imagine that the highest frequency in the Wigner transform is also the Nyquist frequency, or pi/(delta x1).  Why don't you try that first.
