### ISSUE TITLE
[Consortium] Access to full version of Osiris

### ISSUE THREAD

**Issue by OSUhedp** [osiris-code/osiris#3]
We would like to gain access to the advanced diagnostics available in the full version of Osiris. To do this, it looks like we need to join the Osiris consortium at the User level. Please advise. I presume we need to pursue an MoU. Is there a template and to whom do we contact? Thanks.

-Douglass

Douglass Schumacher
Professor of Physics
Ohio State University

**Comment by ricardo-fonseca** [comment]
Thank you for your interest. Please contact me directly using ricardo.fonseca AT tecnico.ulisboa.pt
