### ISSUE TITLE
unphysical divergence for an electron beam propagating in free space

### ISSUE THREAD

**Issue by rl3418** [osiris-code/osiris#5]
Osiris predicted unphysical divergence for an electron beam travelling in free space with gamma=200, n_e~1e20m-3. The momentum along the propagation direction drops rapidly to zero, but for a relativistic beam the longitudinal momentum shouldn't change by much. I performed the same simulations using Smilei. According to Smilei the longitudinal momentum doesn't drop by much, which is exactly what I expect. 

I've attached the results I got from Osiris and Smilei. Under the Osiris folder you could also find information about the libraries I used to compile Osiris. 
 
[potential bug with osiris.zip](https://github.com/osiris-code/osiris/files/13334906/potential.bug.with.osiris.zip)

**Comment by ricardo-fonseca** [comment]
By default, OSIRIS assumes that you are initializing your simulation with a self-consistent field distribution, which is not the case for your input file. This leads to the formation of non-physical EM fields, that will eventually break up your beam. I would recommend that you check the documentation on how to initialize the beam fields properly. You should also use the moving window along x, not y.
