### ISSUE TITLE
Pure function related to new intel compiler

### ISSUE THREAD

**Issue by donglai96** [osiris-code/osiris#8]
When I compile the open source osiris on with ifx (IFX) 2023.2.0 20230721, seems there will be a bug due to recent version:
```
spec/diagnostics/os-spec-rawdiag.f03(52): error #7508: A specification functionmust be a pure function. [GET NX DIMS]real(p_k_fparse),dimension(p_p_dim + spec%get_n_x_dims()+ 2):: raw_var
spec/diagnostics/os-spec-rawdiag.f03(308): error #7588: A specification functionmust be a pure function.[GET NX DIMS]type( t _diag_dataset ),dimension( spec%get_n_x_dims()+ p_p dim + 3 ):: datasets
compilation aborted for os-spec-rawdiag.f03(code 1)
```
The solution might be change the function get_n_x_dims in the os-spec-define.f03 to pure function get_n_x_dims

The compiler error is similar to this: https://community.intel.com/t5/Intel-Fortran-Compiler/Using-results-of-impure-functions-in-automatic-allocation/m-p/1458720

**Comment by romanlee** [comment]
@donglai96, thanks for pointing this out. I agree with your suggested solution. This is fixed in #9. We'll merge this soon, in the meantime please feel free to incorporate this change yourself or checkout that branch.
